### ISSUE TITLE
Create first draft of requirements

### ISSUE THREAD

**Issue by iTech75** [awesome-possums/swe574#1]
This is the control issue of other sub requriment elicitation tasks:

In the second week of the project, team must prepare first draft of requirements. 
Requirements will be created on wiki site.
All requirements must have an identifier.
A proper language must be used (shall-should)

:dart: 1h

- [x] Tekin has created
- [x] Emre has created
- [x] Irmak has created
- [x] Çağla has created
- [x] Yusuf has created
- [x] Mete has created

**Comment by irmakcakmak** [comment]
@awesome-possums/possums test mesajı

**Comment by iTech75** [comment]
Done for the first week :clock1: 1h
