### ISSUE TITLE
Create RSD Document V1

### ISSUE THREAD

**Issue by iTech75** [awesome-possums/swe574#10]
RSD document will be prepared using the proposed initial requiremets on the related page. This document shall include the following standarts:

- [x] use of shall/should

- [x] Every requirement will be labeled with "R-" initial followed by the number of the requirement in three digits: ex: R-010, R-120, sub requirements will be label as R-011 which is sub req of R-010. Sample tree structure is below:

R-010
R-020
  R-021
  R-022
R-030
R-040
..
..
..

- [x] RSD document will be created in the wiki site of the repository. Name of the page is "Project RSD"

- [x] RSD will include some headers. Sample header tree is below:

Table of Contents
Introduction
Definitions
Functional Requirements
Non-functional Requirements
References

:dart: 4 h

**Comment by caglasanlibayrak** [comment]
First version of Requirement Elicitation Document is available on Wiki page.

https://github.com/awesome-possums/swe574/wiki/Project-RSD

:clock330: 3.5 h
