### ISSUE TITLE
Sparql Query gives error

### ISSUE THREAD

**Issue by uskudarli** [awesome-possums/swe574#106]
When I try the default SPARQL query I get the following error:

Error in server, null lexical form for literal

(First make sure they work. Then,  maybe you should provide working SPARQL queries for standard type of queries. )

**Comment by iTech75** [comment]
bug is confirmed! working on it...

**Comment by iTech75** [comment]
Bug was related to data and missing null check in the code. So, null check added to fix the bug. Pushing new version to the production

**Comment by iTech75** [comment]
Default query (as you click the search button with and empty or '}') will list all the heritage items which is equivalent of;

SELECT ?x ?title ?description ?id
WHERE {
?x  <http://purl.org/dc/elements/1.1/title> ?title .
?x  <http://purl.org/dc/elements/1.1/description> ?description .
?x  <http://52.58.125.4:9000/rdf/id> ?id .
}


To search for a specific title, you could;

SELECT ?x ?title ?description ?id
WHERE {
?x  <http://purl.org/dc/elements/1.1/title> ?title .
?x  <http://purl.org/dc/elements/1.1/description> ?description .
?x  <http://52.58.125.4:9000/rdf/id> ?id .
?x  <http://purl.org/dc/elements/1.1/title> "Talakadu - The mysterious Temples" .
}

or 

just the where condition;
?x  <http://purl.org/dc/elements/1.1/title> "Talakadu - The mysterious Temples" .

Please do not forget the "." at the end of the every where condition

Another sample is below:

SELECT ?x ?title ?description ?id
WHERE { 
?x  <http://purl.org/dc/elements/1.1/title> ?title .
?x  <http://purl.org/dc/elements/1.1/description> ?description .
?x  <http://52.58.125.4:9000/rdf/id> ?id .
FILTER regex(?title,  "talakadu", "i") .
}

or just

FILTER regex(?title,  "talakadu", "i") .

Here we can search in strings using regex, this example looks for and RDF of which title contains a string of "talakadu". "i" parameter indicates that search should be case insensitive.

**Comment by iTech75** [comment]
:clock1: 30min

**Comment by uskudarli** [comment]
OK. Got it to work.
