### ISSUE TITLE
Create Mockup screens

### ISSUE THREAD

**Issue by iTech75** [awesome-possums/swe574#11]
Mockup screens for the following functionalities will be created:

- [x] Main heritage view on web

- [x] Main heritage view on mobile

- [x] Main Search view on web

**Comment by emreinan34** [comment]
:target: 4h

**Comment by iTech75** [comment]
No need for mobile mock-ups

**Comment by emreinan34** [comment]
Web & Mobile mockups (including revisions): :clock10: 20h

**Comment by emreinan34** [comment]
Web & Mobile mockups (including revisions): :clock10: 20h
