### ISSUE TITLE
Create web project structure

### ISSUE THREAD

**Issue by iTech75** [awesome-possums/swe574#14]
Web project (Java Spring project) will be created. Project shall include the following packages:

- [ ] Maven

- [ ] Spring MVC 4 project

- [ ] Jackson package (for JSON conversions)

- [ ] Bootstrap + JQuery

- [ ] Hibernate

This project shall server both the web pages (jsp) and API (REST services)

**Comment by irmakcakmak** [comment]
We decided to use Play Framework which also uses Spring Framework for dependency injection. I created development environment using vagrant. Vagrant standardises development environment on each developer's machine, therefore "... but it works on my machine!" problem is greatly reduced. I documented reasons I picked Play in issue #22.

**Comment by irmakcakmak** [comment]
:dart: :clock8:
