### ISSUE TITLE
about the members of velvet:date

### ISSUE THREAD

**Issue by emreinan34** [awesome-possums/swe574#34]
Hi,
I think that instead of velvet:datetime we need to have velvet:begindatetime and velvet:enddatetime because in a case like the one below, end date of the event must also be displayed in the user interface. Currently, we can only display the beginning date of the event to the user, which is 1939-10-01T00:00:00.00000 (stored in velvet:datetime below).

velvet:date

|Properties|Value type|Cardinality|
|----------|------------|-----------|
|**velvet:period**|literal or reference| WW2|
|**velvet:datetime**|literal| 1939-10-01T00:00:00.00000|
|**velvet:begindate**|literal| 1939|
|**velvet:enddate**|literal| 1945|

Emre

**Comment by iTech75** [comment]
Begin date and enddate ar not supposed to be shown end users. They are included just to simplify search.
